services:
  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: src/BookingService.API/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      ConnectionStrings__LocalConnections: "Server=sqlserver,1433;Database=BookingDb;User Id=sa;Password=${MSSQL_SA_PASSWORD:-YourStrong@Passw0rd};TrustServerCertificate=True;"
      ASPNETCORE_Kestrel__Endpoints__Http__Url: "http://+:8080"
      Redis__Connection: "redis:6379"
      JWT__Issuer: "http://localhost:8080"
      JWT__Audience: "http://localhost:8080"
      JWT__SigningKey: "bnf8u3y4gb45687bf8y34gw4b87oewgb4897ofjh3789f4dbhnw738034jmdct9348htjfgjakd973gfhaoml9zfhbvn4o87q"
    ports:
      - "8080:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-YourStrong@Passw0rd}"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mssql-data:
