name: .NET Core CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore BookingService.sln

    - name: Build project
      run: dotnet build BookingService.sln --no-restore --configuration Release

    - name: Run Unit Tests
      run: dotnet test tests/BookingService.UnitTests/BookingService.UnitTests.csproj --no-build --configuration Release

    - name: Run Integration Tests
      run: dotnet test tests/BookingService.IntergationTests/BookingService.IntegrationTests/BookingService.IntegrationTests.csproj --no-build --configuration Release