name: .NET Core CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore BookingService.sln

    - name: Run Unit Tests
      # Будуємо і тестуємо тільки юніт-проєкт в Release
      run: dotnet test tests/BookingService.UnitTests/BookingService.UnitTests.csproj --configuration Release --verbosity normal

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore BookingService.sln

    - name: Run Integration Tests
      # Прибираємо --no-build, щоб dotnet сам правильно зібрав контекст тестів на сервері.
      # Зверни увагу на шлях: перевір у себе в репозиторії, чи папка дійсно пишеться як "IntergationTests" з помилкою.
      run: dotnet test tests/BookingService.IntergationTests/BookingService.IntegrationTests/BookingService.IntegrationTests.csproj --configuration Release --verbosity normal